### PR TITLE
exomeseq vcf sqlite3 database generation - PLEASE DO NOT MERGE UNTIL TESTED

### PR DESCRIPTION
**Pull request by nikhilbg**
This needs to be tested further. The lines of code that generate the database have been added to each rule. In short, the rule now generates a sqlite commands file which includes the table declaration commands for headers and importing commands. The temp files generated are generated after some processing and used for importing into sqlite3. Some of the processing includes removing special characters from the headers. Additionally, since I noticed some columns are duplicates, or at least have duplicate headers.. I am using R to remove some of the said duplicated rows. Another option would be to change the R script that I am using (dedupcols.R) and comment out the deduplication step (line 2), and change check.names to True in the table import step. I believe this will force the column names to be appended with a unique number if there are duplicates, and thus could solve the issue in a workaround way without removing columns. I also finally remove the header row in the temp file before importing, after the header information is already sent to the sqlite commands script. The file generated is called vcf.db. NOTE. it may be best to add a line before all of this to remove the file vcf.db if it already exists. This is because if the pipeline is re-run again sqlite3 will throw an error since the file already exists. If there are any bugs with these steps then it should not be a problem as Snakemake will still find the output files frmo the previous lines of code. If there are any issues please contact me at nikhilbg96@gmail.com. **You will also find the VariantFilteringTool repository updated with a version that is compatible with the vcf.db file created here.**

_This pull request is being submitted now since I will be leaving soon, and if this works then you do not have to wait for me to pull. If there are any bugs please shoot me an email with the errors. This can be tested by just cloning my Pipeliner fork at github.com/nikhilbg/Pipeliner_

**If Justin can find a way to deal with duplicated column names before hand then you can remove the R script and remove the call to the R script and everything will work perfectly. This is the cleanest solution if my brute force hack does not work.**

### CODE REVIEW

**Comment by joshuabhk** [comment]
I am just wondering why we are making vcf into sql? Is there any specific
need for it? Other than the formatting issue? If fast random access is the
issue, there are better ways than using sqlite.

Bong-Hyun

**Comment by jlac** [comment]
It serves as the input for the html database tool that we built. It’s searchable and exportable, after we merge the VCF with the annotations we generate. This will be done for all SNPs/INDELs, CNVs, SVs, and gene fusions. The tool will be run from CCBRweb, and the PI or one of us can then open the tool, point to any one of the database files we generate in the pipeline, and start filtering. Then when they’re done filtering, they can export the table.

Justin

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by joshuabhk** [comment]
I see. If it works good for our need, it is fine. If you need some other
necessities or speed issues etc, I may help.

**Comment by jlac** [comment]
Ok, thanks! It seems to be working fine for now, although I still need to test it with a really large VCF (>1 million SNPs across dozens of individuals). It hasn’t been added into any pipelines yet, just merged into the main branch.

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Pull request merged**
